### ISSUE TITLE
Invalid SARIF format

### ISSUE THREAD

**Issue by CallMeGreg** [microsoft/ApplicationInspector-Action#12]
When running [this App Inspector workflow](https://github.com/callmegreg-demo-org/demo-repo/blob/main/.github/workflows/App-Inspector.yml), the attempted SARIF upload to GitHub code scanning fails due to improper SARIF format:

```
Unable to upload "AppInspectorResults.sarif" as it is not valid SARIF:
- instance is not allowed to have the additional property "SarifNodeKind"
- instance is not allowed to have the additional property "SchemaUri"
- instance is not allowed to have the additional property "Version"
- instance is not allowed to have the additional property "Runs"
- instance is not allowed to have the additional property "InlineExternalProperties"
- instance is not allowed to have the additional property "PropertyNames"
- instance is not allowed to have the additional property "Tags"
- instance requires property "version"
- instance requires property "runs"
```

After reviewing the [SARIF spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.pdf) and testing with the [SARIF validator](https://sarifweb.azurewebsites.net/Validation), I believe the following changes will help fix the issue:
1. Update all key names to camelCase values (starting with lowercase)
2. Remove the `SarifNodeKind` and `PropertyNames` key/value pairs
3. Change the `SchemaUri` key to `$schema`
4. Update the `version` value from `2` to `"2.1.0"`

**Comment by CallMeGreg** [comment]
cc: @gfs

**Comment by cqueern** [comment]
Important capability, look forward to seeing how this shakes out

**Comment by gfs** [comment]
@CallMeGreg 

Thanks for the feedback. I should be able to improve the sarif output from application inspector.  It may be mostly an issue of updating the sarif sdk we use.

I'd like to understand your use case better - the core rule set for application inspector isn't really intended for use with the GitHub sarif upload tool, as application inspector findings are not considered security issue. I'm not sure that they would be meaningful in the context of the GitHub security issues panel. 

If you are using custom rules and want those results to show up in the GitHub security issues pane I would instead recommend using DevSkim or the DevSkim action. DevSkim now uses essentially the same rule format and rule processor. Any work you've done to develop custom AI rules should carry over to DevSkim.

**Comment by CallMeGreg** [comment]
So glad you asked 😄 to be honest, I'm also thinking code scanning is not the right home for app inspector alerts, but I've been working with @cqueern to test that hypothesis. The end goal is to get visibility, at scale, into the behavior of source code across a GitHub organization or enterprise, and monitor changes over time.

I'm thinking it's more likely we pivot to a solution that involves uploading to a central location (e.g. Azure) and do data analysis from there. In that case, we may opt for json over sarif, but wanted to first push the limits of analysis in GitHub.

Would love to hear any thoughts you might have about how to better go about a solution with this goal in mind 🙏

**Comment by CallMeGreg** [comment]
@gfs Thinking more about the nature of App Inspector rules, perhaps it would make sense to set the `severity` of each finding to `note`?

**Comment by gfs** [comment]
@callmegreg

Thanks. I think that context helps, and that sounds like an interesting project.

I think I would recommend that central repository approach you mention - with the caveat that Sarif is likely a better format for that than the JSON. The AppInspector JSON ouptut is a proprietary to appinspector and may be subject to change in the future. Sarif is also technically just a subset of json - so if you'd planned to analyze it using json parsing tools that would still work with a sarif log - but with a more formally defined schema. 

I do plan to fix the issues you've identified with the sarif format we currently produce, thanks for pointing those out, and to indicate that sarif is a valid output format in the action per your submitted PR.

For the severity, using note may be the right approach, ~appinspector does not have a severity flag per se that maps cleanly~ (because the appinspector detections are not "security issues") - but we can instead save the appinspector confidence values in the additional properties bag.

Edit: AppInspector rules do have severity values, I think I was confusing this with the confidence field that is top level in DevSkim rules.

**Comment by CallMeGreg** [comment]
Thank you @gfs!! Appreciate all of your help with this ✨

Also realizing I misquoted the spec, I should've said `level` instead of `severity`. I agree with the way you put it, I'm thinking of these results as code analysis notes, rather than security issues. I still have some hope that the metrics & filtering available from the GitHub security overview page might be valuable for analysis of app inspector findings across an org or enterprise. We shall see!

**Comment by gfs** [comment]
The current behavior is to set the level based on the ai severity. I will discuss with the team if it makes sense to switch to note universally and provide the AI severity in the prop bag today. 

Plan to merge these changes this week.
